version: '3'

services:
  mysql:
    image: mysql:5.7.22
    container_name: faveo_mysql
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: faveo
      MYSQL_DATABASE: faveo
      MYSQL_USER: faveo
      MYSQL_PASSWORD: faveo
    # ports:
    #   - "3306:3306"
    networks:
      - proxy

  faveo:
    container_name: faveo
    depends_on:
      - mysql
    image: ladybirdweb/faveo-docker
    links:
      - mysql:mysql
    ports:
      - "8099:80"
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.faveo.rule=Host(`faveo.local`)
    # env_file:
    #   - ./.env
    networks:
      - proxy
    environment:
      - APP_DEBUG=true

volumes:
  db_data:

networks:
  proxy:
    external: true
